lib/xcov/model/function.rb, lib/xcov/model/report.rb, lib/xcov/model/source.rb, lib/xcov/model/target.rb, lib/xcov/runner.rb
The current JSON report just spits out the raw report received
from xcov-core. As such, the coverage total, and the coverage
per target values in the JSON report are different from those in
the HTML or Markdown reports.
This patch creates a new JSON report using the same data that is
used for the HTML and Markdown reports. Targets which are skipped
(such as test targets) are not included in the output, and files
that have been ignored are marked with "ignored": true in the file
object and are not considered when calculating per target or per
report totals.
=> Make JSON report honour ignored files in coverage

lib/xcov/model/base.rb
In our project, ignored files show up in Github (via [danger-xcov](https://github.com/nakiostudio/danger-xcov)) like so:
The empty backticks in the coverage column are unfortunate, and I'm not sure it makes sense to display a coverage emoji for ignored files.
To that end:
- https://github.com/nakiostudio/xcov/commit/1e3cf4865dbc547debdbe813de568cb598ecb12b outputs a hyphen for ignored files' coverage, instead of an empty string. As noted in the commit message, a similar change (transforming an empty string to “-”) could instead be made in `markdown_value` in `source.rb`.
- https://github.com/nakiostudio/xcov/commit/08317ada2164419aece94972c4d7df4e84b51e83 should return an empty string instead of an emoji for ignored files.
=> Display improvements for ignored files

lib/xcov/options.rb
If 'derived_data_path' argument was indicated but the path was inexistent,
we got this message:
> Unable to find any .xccoverage file.
> Make sure you have enabled 'Gather code coverage' setting on your scheme settings.
> Alternatively you can provide the full path to your .xccoverage file.
This patch adds a verification block to 'derived_data_path' option in
order to give faster and more accurate feedback.
=> Verify 'derived_data_path' option

CHANGELOG.md, lib/xcov/model/report.rb
When using xcov as a gem from something like Danger managing excluded targets as comma seperated string becomes cumbersome.
This change adds handling for when targets is passed in as an array it returns it directly, otherwise the behaviour is unchanged.
=> Excluded targets option array support

CHANGELOG.md, README.md, lib/xcov/model/report.rb, lib/xcov/options.rb
With Xcode 8 it seems that coverage is generated for all targets in an app even it the schem for that target has coverage turned off.
When there are a lot of targets, for exampl projects that use cocoapods, an inclusion list is much easier to maintain than an exclusion list.
With this change a list of targets to include in the report can be specified as well as the exclusion list that existed previously.
=> Add include targets option

lib/xcov/ignore_handler.rb, lib/xcov/options.rb
This change is made in order to fix a bug when 'xcov' gem is used
as a dependency and 'source_directory' is not explicitly defined.
This resolves #52.
=> Compute 'source_directory' default value when requested

xcov.gemspec
With the recent [mono gem release](https://github.com/fastlane/fastlane/releases/tag/2.0.0) you'll need to remove _fastlane_core_ as dependency. 
Sorry I submitted this PR on such a short notice, I submitted PRs on various projects, but for some reasons I forgot to do it for this widely used one. 
Please give this a try with _fastlane_ 2.0, make sure everything works as usual and push a new release  👍
Thanks for building this!
=> Update gemspec to support fastlane 2.0

lib/xcov/model/target.rb
Sorting by coverage got broken in v0.6 when support for ignored files was added.
This should return sorting behavior back keeping ignored files at the end of the list.
This resolves #61.
=> Fix sorting files by coverage

README.md, lib/xcov.rb, lib/xcov/model/report.rb, lib/xcov/options.rb, lib/xcov/project_extensions.rb, xcov.gemspec
This adds an option which being set ignores the targets of auxiliary projects in a workspace.
For example, by setting `--only_project_targets`, xcov will ignore Pods targets.
=> Display the coverage only for main project targets

README.md, lib/xcov/ignore_handler.rb
As file system on macOS is case insensitive, we can ignore the cases
in order to prevent the situations when `test.txt` doesn't match `Test.txt`
This should prevent the kind of issues we had in #74.
=> Handle ignores case insensitively

README.md
fastlane manages `scan` in a mono repo now.
=> Fix link to fastlane scan

lib/xcov/options.rb
This fixes the issue when path to the folder containing ignore file
was incorrect if Fastlane folder was hidden (.fastlane)
=> Fix the path to containing folder

lib/xcov/coveralls_handler.rb
Partially fixes #116
The fix makes it not crash, but doesn't fix the source of the problem. `lines` is always nil when using the new `xccovreport` files.
=> Do not crash when missing lines for coveralls

README.md, lib/xcov/manager.rb, lib/xcov/options.rb
I was having an issue where Coveralls was being submitted automatically due to the presence of the environmental variables. This breaks backwards compatibility if you were relying on the automatic assumption of Coveralls via the environment, but I personally feel like being explicit is better.
=> Add option to disable automatic Coveralls submission

lib/xcov/options.rb
Yikes, found some problems with #118. Looks like the xcov / fastlane options parser doesn't accept the "type" parameter for some reason, although I've used it elsewhere in a recent fastlane plugin, and complains about the "." in the description.
=> Hotfix for "disable coveralls" PR

lib/xcov/coveralls_handler.rb
Hi,
I found Coveralls handler outputs external command error like the below
```
fatal: Cannot open 'CI2Go/View': No such file or directory
```
ref: https://circleci.com/gh/ngs/ci2go/785
This happens project code contains folders with spaces.
So I double-quoted file path passing to `git hash-object` command.
Please merge this if you'd like.
Thanks,
=> Quote file path passing to `git hash-object` command

lib/xcov/manager.rb
xcov ruby 2.6.0 issue: ArgumentError: [!] incomplete format specifier; use %% (double %) instead
Replace % to %% (double %) in error message
=> #145: ArgumentError: [!] incomplete format specifier; use %% (double %) instead

lib/xcov/manager.rb, lib/xcov/options.rb, xcov.gemspec
See 👉  https://github.com/fastlane-community/danger-xcov/issues/26
- Updated `:xccov_file_direct_path` to accept `.xcresult` extension
- Uses new https://github.com/fastlane-community/xcresult gem to parse `.xcresult` file and export the `.xccovreport` files to a destination directory when:
- `:xccov_file_direct_path` is given and ends in `.xcresult`
- no `.xccoverage` or `.xccovreport` files are found 
Update your `Gemfile` to 👇 and run `bundle install` or `bundle update xcov`
```
gem 'xcov`, :git => 'https://github.com/fastlane-community/xcov.git', :branch => 'joshdholtz-xcresult-support'
```
=> Add Xcode11 xcresult support

lib/xcov/manager.rb, xcov.gemspec
Fixes #157
- Updates `xcresult` to `0.2.0` which introduces `export_xccovarchives`
- Now calls `export_xccovarchives` along with `export_xccovreports`
- Exports both of these to output directory
```sh
[17:28:30]: $ xcodebuild -showBuildSettings -workspace ../../myproject/myproject-ios/Example/myproject.xcworkspace -scheme myproject-Example
2019-10-01 17:28:32.422 xcodebuild[56457:3813433]  DTDeviceKit: deviceType from 00008006-001573C02EE2002E was NULL
2019-10-01 17:28:32.528 xcodebuild[56457:3813289] [MT] DTDeviceKit: deviceType from 00008006-001573C02EE2002E was NULL
2019-10-01 17:28:32.535 xcodebuild[56457:3813289] [MT] DTDeviceKit: deviceType from 00008006-001573C02EE2002E was NULL
2019-10-01 17:28:32.561 xcodebuild[56457:3813289] [MT] DTDeviceKit: deviceType from …
```
=> Export .xccovarchive and .xccovreport

lib/xcov/model/target.rb
> This is a fix for a long-running issue where in a bid to bring xcov values closer to XCode’s report, file and folder exclusions were being ignored. i.e. Exclusions were always considered when calculating the total coverage percentage.
>
> This commit reverts 2c68bfb which introduced the issue.
>
> For more information see: https://github.com/fastlane-community/xcov/issues/130
I've tested this branch, it works great.
=> Calculate coverage percentage respecting exclusions

lib/xcov/model/source.rb
Adds the file path when generating json reports (via `--json_report`).
```json
"files": [
{ 
"name": "MyFile.swift",
"coverage": 0,
...
```
```json
"files": [
{ 
"name": "MyFile.swift",
"path":"/Users/me/project/MyFile.swift",
"coverage": 0,
...
```
To assist automated tooling, it's helpful to know the path of the files. In larger projects, it's not uncommon to have duplicate file names across targets. Reconciling the coverage `name` with the actual file requires either a) parsing the Xcode coverage reports ourselves or b) keeping track of the corresponding target and parsing Xcode project files. Both options seem pretty unfortunate.
- Should this be gated behind a flag?
- Opinion: Adding this field will increase the size of the generated json reports but I don't think the amount will be …
=> Add file path to json output

lib/xcov/model/report.rb, lib/xcov/options.rb
removes targets with 0% coverage from final report
=> Support for include_zero_targets option

.github/workflows/test.yml, Rakefile, lib/xcov/manager.rb, lib/xcov/options.rb, spec/manager_spec.rb, spec/spec_helper.rb, spec/xcov_spec.rb, xcov.gemspec
Close #195 
- Define `xccov_file_direct_path` option to receive both a string and an array of strings.
- To not break backward compatibility, I didn't change the option key (ideally it should be plural though).
- Set up rspec and CI using GitHub Actions.
- Add minimal specs to check if `xccov_file_direct_path` option works.
=> Accept multiple xccov_file_direct_path

lib/xcov/options.rb
Adding `use_system_scm` option because `xcodebuild` was failing to resolve Swift Package dependencies on our CI.
=> Adding use_system_scm option

lib/xcov/manager.rb
Addresses this [issue](https://github.com/fastlane-community/xcov/issues/181).
It now adds the average coverage value of the report at the end of the coverage report to the console. 
```
+---------------------+--------+
|     xcov Coverage Report     |
+---------------------+--------+
| A.framework               | 12.34% |
| B.framework               | 56.78% |
+---------------------+--------+
```
```
+---------------------+--------+
|     xcov Coverage Report     |
+---------------------+--------+
| A.framework               | 12.34% |
| B.framework               | 56.78% |
| Average Coverage     | xx.yy%  |
+---------------------+--------+
```
=> Display average coverage in log
